FROM python:3.10-slim

WORKDIR /app
COPY app_ui.py ui_requirements.txt ./
RUN pip install --no-cache-dir -r ui_requirements.txt

EXPOSE 8501
CMD ["streamlit", "run", "app_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
